### PR TITLE
Renames to get up to speed with master 1acc76f

### PR DESCRIPTION
**Pull request by RicardRC**
Rename Transform to Transform3D
Rename transform.h to transform_3d.h
Rename .instance() to .instantiate()
Rename set_translation( to set_position(
Rename Reference to RefCounted
Rename Variant::QUAT to Variant::QUATERNION
Rename Variant::TRANSFORM to Variant::TRANSFORM3D

### CODE REVIEW

**Comment by AndreaCatania** [comment]
Great Pr! can you please update the readme.md file so it has the latest commit hash? https://github.com/GodotECS/godex#the-tested-godot-version

**Comment by AndreaCatania** [comment]
The CI check fails just because we need to also update this https://github.com/GodotECS/godot with latest Godot commit. So the CI uses the correct Godot version.

**Comment by RicardRC** [comment]
I don't think it's ready yet, the EditorPropertyResource::setup change of signature is still pending, I'll investigate more tomorrow, I may need help with getting providing the correct arguments.

**Comment by RicardRC** [comment]
Ok, now should compile and run. Though I'm still not confident in the EditorPropertyResource "setup" signature that I updated, at least compiles and runs. @AndreaCatania maybe you'll want to review that part specifically. I can't update the GodotECS/godot repo, I'll leave that to you :)

**Comment by AndreaCatania** [comment]
Thanks! I'll update godot and run the CI of this PR. It should work, I'll also review this PR again, but in the first pass everything seems fine already :)

**Pull request closed without merging**
